import type { DumbDumbHubPayload, DumbDumbItem, DumbDumbList, DumbDumbPurchase } from './api/dumbDumbApi';

export const dumbDumbIconMap: Record<string, string> = {
  SPOON: '🥄',
  SHADES: '🕶️',
  INCENSE: '🪔',
  BOTTLE: '🧴',
  PEBBLE: '🪨',
  SPARK: '🪩',
  CAPE: '🧥',
  TOTE: '👜',
  MOON: '🌙',
  FOG: '🌫️',
  BOX: '📦',
  HAT: '🎩',
};

export function dumbDumbVisual(item: Pick<DumbDumbItem, 'icon_key' | 'title'>): string {
  return dumbDumbIconMap[item.icon_key || ''] || '✨';
}

export function formatMoney(cents: number, currency = 'usd'): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency.toUpperCase(),
    maximumFractionDigits: 0,
  }).format(cents / 100);
}

export function formatRelativeTime(iso?: string | null): string {
  if (!iso) return 'just now';
  const diffMs = Date.now() - new Date(iso).getTime();
  const minutes = Math.max(1, Math.round(diffMs / 60000));
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.round(hours / 24);
  return `${days}d ago`;
}

const demoItems: DumbDumbItem[] = [
  {
    id: 1,
    list_id: 1,
    title: 'Gold-Plated Emotional Support Spoon',
    parody_description: 'For dramatically stirring exactly one feeling at a time.',
    source_site_name: 'Sunday Ritual',
    icon_key: 'SPOON',
    price_cents: 1800,
    currency: 'usd',
    actual_funds_label: 'Actually funds',
    impact_title: '20 meals',
    impact_description: 'Stocks staple pantry packs for households riding out the week.',
    quantity_limit: 12,
    quantity_sold: 4,
    quantity_remaining: 8,
    is_active: true,
    is_sold_out: false,
    destination_pool: { id: 1, slug: 'meals', name: 'Meals Pool', category: 'food', current_balance_cents: 42000 },
  },
  {
    id: 2,
    list_id: 1,
    title: 'Tactical Nightclub Sunglasses',
    parody_description: 'Sharp enough for vibes, soft enough for daylight logistics.',
    source_site_name: 'Light Wash Studio',
    icon_key: 'SHADES',
    price_cents: 2400,
    currency: 'usd',
    actual_funds_label: 'Actually funds',
    impact_title: '1 week transport',
    impact_description: 'Covers local transport for appointments, school runs, or shift access.',
    quantity_limit: 12,
    quantity_sold: 3,
    quantity_remaining: 9,
    is_active: true,
    is_sold_out: false,
    destination_pool: { id: 2, slug: 'transport', name: 'Transport Pool', category: 'mobility', current_balance_cents: 38000 },
  },
  {
    id: 3,
    list_id: 1,
    title: 'Crypto-Blessed Incense Sticks',
    parody_description: 'Smells like optimism and a terrible podcast pitch.',
    source_site_name: 'Tender Modern',
    icon_key: 'INCENSE',
    price_cents: 2200,
    currency: 'usd',
    actual_funds_label: 'Actually funds',
    impact_title: 'GP visit support',
    impact_description: 'Offsets out-of-pocket care for a same-week clinic visit.',
    quantity_limit: 12,
    quantity_sold: 1,
    quantity_remaining: 11,
    is_active: true,
    is_sold_out: false,
    destination_pool: { id: 3, slug: 'gp-visit', name: 'GP Visit Pool', category: 'health', current_balance_cents: 27000 },
  },
  {
    id: 4,
    list_id: 1,
    title: 'Influencer Hydration Aura Bottle',
    parody_description: 'Now with extra electrolytes for posting through adversity.',
    source_site_name: 'Soft Utility',
    icon_key: 'BOTTLE',
    price_cents: 2600,
    currency: 'usd',
    actual_funds_label: 'Actually funds',
    impact_title: 'Community fridge restock',
    impact_description: 'Refills cold storage with fresh produce, milk, and quick meals.',
    quantity_limit: 12,
    quantity_sold: 2,
    quantity_remaining: 10,
    is_active: true,
    is_sold_out: false,
    destination_pool: { id: 4, slug: 'community-fridge', name: 'Community Fridge', category: 'food', current_balance_cents: 31000 },
  },
  {
    id: 5,
    list_id: 2,
    title: 'CEO Mindfulness Pebble',
    parody_description: 'Fits in your palm and absolutely cannot solve structural precarity.',
    source_site_name: 'North Shelf',
    icon_key: 'PEBBLE',
    price_cents: 3200,
    currency: 'usd',
    actual_funds_label: 'Actually funds',
    impact_title: 'Shelter night',
    impact_description: 'Funds one safe overnight stay plus basic toiletries.',
    quantity_limit: 12,
    quantity_sold: 2,
    quantity_remaining: 10,
    is_active: true,
    is_sold_out: false,
    destination_pool: { id: 5, slug: 'shelter-night', name: 'Shelter Night Pool', category: 'housing', current_balance_cents: 46000 },
  },
  {
    id: 6,
    list_id: 2,
    title: 'Limited Edition Vibe Stabilizer',
    parody_description: 'Guaranteed to do less than a rent top-up and cost the same.',
    source_site_name: 'Edition Nine',
    icon_key: 'SPARK',
    price_cents: 4000,
    currency: 'usd',
    actual_funds_label: 'Actually funds',
    impact_title: "Women's emergency fund",
    impact_description: 'Supports emergency cash grants for urgent safety planning.',
    quantity_limit: 12,
    quantity_sold: 1,
    quantity_remaining: 11,
    is_active: true,
    is_sold_out: false,
    destination_pool: { id: 6, slug: 'womens-emergency', name: "Women's Emergency Fund", category: 'safety', current_balance_cents: 52000 },
  },
];

export const demoLists: DumbDumbList[] = [
  {
    id: 1,
    node_id: 1,
    owner_user_id: 101,
    title: "Sol's deluxe non-essentials",
    slug: 'sol-deluxe-non-essentials',
    intro_text: 'Excessive nonsense on the surface, direct mutual aid underneath.',
    parody_disclaimer: 'Dumb Dumb Mode is transparent satire. You are not buying a real product. Your contribution funds the real mutual-aid outcome shown on each item.',
    is_public: true,
    is_active: true,
    owner: { id: 101, username: 'dd_sol', pseudonym: 'Sol Threadline', role: 'organizer' },
    item_count: 4,
    items: demoItems.slice(0, 4),
  },
  {
    id: 2,
    node_id: 1,
    owner_user_id: 102,
    title: "Marlow's emergency glamour basket",
    slug: 'marlow-emergency-glamour-basket',
    intro_text: 'A parody shelf for funding transport, care, and community restocks.',
    parody_disclaimer: 'Dumb Dumb Mode is transparent satire. You are not buying a real product. Your contribution funds the real mutual-aid outcome shown on each item.',
    is_public: true,
    is_active: true,
    owner: { id: 102, username: 'dd_marlow', pseudonym: 'Marlow Fern', role: 'organizer' },
    item_count: 4,
    items: [
      demoItems[4],
      demoItems[5],
      {
        ...demoItems[0],
        id: 7,
        list_id: 2,
        title: 'Ceremonial Startup Cape',
        icon_key: 'CAPE',
        price_cents: 3000,
        impact_title: 'School supplies pack',
        impact_description: 'Covers notebooks, pens, and classroom basics for one child.',
        destination_pool: { id: 7, slug: 'school-supplies', name: 'School Supplies Pool', category: 'education', current_balance_cents: 28000 },
      },
      {
        ...demoItems[1],
        id: 8,
        list_id: 2,
        title: 'Velvet Apocalypse Tote',
        icon_key: 'TOTE',
        price_cents: 2800,
        impact_title: 'Meal pantry bundle',
        impact_description: 'Provides shelf-stable groceries and easy-cook dinner kits.',
      },
    ],
  },
  {
    id: 3,
    node_id: 1,
    owner_user_id: 103,
    title: "Nia's prestige nonsense registry",
    slug: 'nia-prestige-nonsense-registry',
    intro_text: 'Ridiculous wrappers around concrete help people can use this week.',
    parody_disclaimer: 'Dumb Dumb Mode is transparent satire. You are not buying a real product. Your contribution funds the real mutual-aid outcome shown on each item.',
    is_public: true,
    is_active: true,
    owner: { id: 103, username: 'dd_nia', pseudonym: 'Nia Vale', role: 'organizer' },
    item_count: 4,
    items: [
      {
        ...demoItems[1],
        id: 9,
        list_id: 3,
        title: 'Executive Moonbeam Subscription',
        icon_key: 'MOON',
        price_cents: 3500,
        impact_title: 'Transport pass top-up',
        impact_description: 'Keeps someone moving between work, care, and community support.',
      },
      {
        ...demoItems[3],
        id: 10,
        list_id: 3,
        title: 'Hyperlocal Prestige Fog',
        icon_key: 'FOG',
        price_cents: 2100,
        impact_title: 'Fresh food restock',
        impact_description: 'Replenishes a community fridge with fruit, greens, and proteins.',
      },
      {
        ...demoItems[2],
        id: 11,
        list_id: 3,
        title: 'Algorithmic Feelings Starter Pack',
        icon_key: 'BOX',
        price_cents: 2700,
        impact_title: 'Clinic access support',
        impact_description: 'Helps cover a consultation and prescription pickup trip.',
      },
      {
        ...demoItems[4],
        id: 12,
        list_id: 3,
        title: 'Diamond-Certified Side Quest Hat',
        icon_key: 'HAT',
        price_cents: 3300,
        impact_title: 'Safe night indoors',
        impact_description: 'Supports one emergency accommodation placement.',
      },
    ],
  },
];

export const demoHubPayload: DumbDumbHubPayload = {
  hero: {
    title: 'Dumb Dumb Mode',
    subtitle: 'Transparent satire for mutual aid. Pick a parody item, see the real impact, and fund the pool named on the card.',
    disclaimer: 'Dumb Dumb Mode is transparent satire. You are not buying a real product. Your contribution funds the real mutual-aid outcome shown on each item.',
  },
  stats: {
    lists: demoLists.length,
    items: demoLists.reduce((sum, list) => sum + (list.items?.length || 0), 0),
    total_raised_cents: 124000,
    recent_purchases: 3,
  },
  featured_lists: demoLists,
  featured_items: demoItems,
  activity_feed: [
    {
      id: 1,
      buyer_name: 'Alex',
      parody_title: 'Tactical Nightclub Sunglasses',
      impact_title: '1 week transport',
      amount_cents: 2400,
      pool_name: 'Transport Pool',
      created_at: new Date().toISOString(),
      message: 'Alex bought Tactical Nightclub Sunglasses and funded 1 week transport',
    },
    {
      id: 2,
      buyer_name: 'Sam',
      parody_title: 'Gold-Plated Emotional Support Spoon',
      impact_title: '20 meals',
      amount_cents: 1800,
      pool_name: 'Meals Pool',
      created_at: new Date(Date.now() - 1000 * 60 * 52).toISOString(),
      message: 'Sam bought Gold-Plated Emotional Support Spoon and funded 20 meals',
    },
    {
      id: 3,
      buyer_name: 'Lee',
      parody_title: 'Limited Edition Vibe Stabilizer',
      impact_title: "Women's emergency fund",
      amount_cents: 4000,
      pool_name: "Women's Emergency Fund",
      created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      message: "Lee bought Limited Edition Vibe Stabilizer and funded Women's emergency fund",
    },
  ],
  transparency: {
    headline: 'Parody wrapper, real mutual aid destination.',
    body: 'Every card names the real pool and impact before checkout.',
    points: [
      'Every card names the real pool and impact before checkout.',
      'Checkout repeats that you are funding the cause, not buying a product.',
      'Receipts, ledger entries, and admin reporting keep the real destination explicit.',
    ],
  },
};

export const demoPurchase: DumbDumbPurchase = {
  id: 42,
  item_id: 2,
  list_id: 1,
  amount_cents: 2400,
  currency: 'usd',
  status: 'paid',
  destination_pool_id: 2,
  receipt_snapshot_json: {
    parody_title: 'Tactical Nightclub Sunglasses',
    actual_cause: '1 week transport',
    impact_description: 'Covers local transport for appointments, school runs, or shift access.',
  },
  buyer: { id: 201, username: 'supporter', pseudonym: 'Alex' },
  owner: demoLists[0].owner,
  item: demoItems[1],
  list: {
    id: 1,
    slug: demoLists[0].slug,
    title: demoLists[0].title,
    parody_disclaimer: demoLists[0].parody_disclaimer,
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};
