// Mock data for graceful fallback when API is unavailable

export const mockPools = [
  {
    id: 1,
    slug: 'relief',
    name: 'Relief Fund',
    description: 'Direct aid for community members',
    balance: 125000,
    targetAmount: 200000,
    allocationPercent: 65,
    trend: 'up' as const,
    trendValue: '+12% this month',
    color: 'sage' as const,
    icon: 'heart' as const,
    sparklineData: [30, 45, 35, 50, 48, 60, 55, 70, 65, 80, 75, 90],
    current_balance_cents: 12500000,
    target_amount_cents: 20000000,
    category: 'relief',
    is_active: true,
  },
  {
    id: 2,
    slug: 'sovereignty',
    name: 'Sovereignty',
    description: 'Land trust & self-governance',
    balance: 89000,
    targetAmount: 150000,
    allocationPercent: 20,
    trend: 'up' as const,
    trendValue: '+8% this month',
    color: 'institutional' as const,
    icon: 'shield' as const,
    sparklineData: [20, 25, 22, 30, 35, 32, 38, 42, 45, 48, 52, 55],
    current_balance_cents: 8900000,
    target_amount_cents: 15000000,
    category: 'sovereignty',
    is_active: true,
  },
  {
    id: 3,
    slug: 'infrastructure',
    name: 'Infrastructure',
    description: 'Physical commons & tools',
    balance: 34000,
    targetAmount: 100000,
    allocationPercent: 15,
    trend: 'neutral' as const,
    trendValue: 'Stable',
    color: 'accent' as const,
    icon: 'sprout' as const,
    sparklineData: [15, 15, 16, 15, 17, 16, 18, 17, 19, 18, 20, 19],
    current_balance_cents: 3400000,
    target_amount_cents: 10000000,
    category: 'infrastructure',
    is_active: true,
  },
];

export const mockReliefRequests = [
  {
    id: '1',
    amount: 2500,
    purpose: 'Emergency rent assistance',
    urgency: 'high' as const,
    status: 'under_review' as const,
    queuePosition: 3,
    totalInQueue: 24,
    submittedAt: '2 days ago',
    estimatedDays: 2,
    anonId: '7X9K2M',
    amount_requested_cents: 250000,
    description: 'Behind on rent due to medical emergency',
    contact_preference: 'in-app',
  },
  {
    id: '2',
    amount: 800,
    purpose: 'Medical expenses',
    urgency: 'medium' as const,
    status: 'pending' as const,
    queuePosition: 8,
    totalInQueue: 24,
    submittedAt: '4 days ago',
    estimatedDays: 5,
    anonId: '3P8Q1R',
    amount_requested_cents: 80000,
    description: 'Prescription medication costs',
    contact_preference: 'email',
  },
  {
    id: '3',
    amount: 1200,
    purpose: 'Utilities support',
    urgency: 'low' as const,
    status: 'approved' as const,
    queuePosition: 0,
    totalInQueue: 24,
    submittedAt: '1 week ago',
    estimatedDays: 0,
    anonId: '9T4W6Y',
    amount_requested_cents: 120000,
    description: 'Electric and water bill assistance',
    contact_preference: 'phone',
  },
];

export const mockMembers = [
  { name: 'Alex Chen', pseudonym: 'River Stone', role: 'validator' as const, impactScore: 2450, tier: 'oak' as const, streakMonths: 8, index: 0 },
  { name: 'Sam Williams', pseudonym: 'Oak Shadow', role: 'organizer' as const, impactScore: 1890, tier: 'oak' as const, streakMonths: 12, index: 1 },
  { name: 'Jordan Lee', pseudonym: 'Moss Walker', role: 'participant' as const, impactScore: 920, tier: 'sapling' as const, streakMonths: 3, index: 2 },
  { name: 'Morgan Taylor', pseudonym: 'Fern Grove', role: 'case_worker' as const, impactScore: 3200, tier: 'redwood' as const, streakMonths: 15, index: 3 },
  { name: 'Casey Park', pseudonym: 'Pine Needle', role: 'participant' as const, impactScore: 450, tier: 'seed' as const, streakMonths: 1, index: 4 },
  { name: 'Riley Jones', pseudonym: 'Cedar Bark', role: 'auditor' as const, impactScore: 2780, tier: 'oak' as const, streakMonths: 10, index: 5 },
  { name: 'Quinn Murphy', pseudonym: 'Willow Branch', role: 'participant' as const, impactScore: 670, tier: 'sapling' as const, streakMonths: 4, index: 6 },
  { name: 'Avery Smith', pseudonym: 'Maple Leaf', role: 'board_member' as const, impactScore: 4100, tier: 'redwood' as const, streakMonths: 24, index: 7 },
];

export const mockStats = {
  totalDistributed: 2480000,
  totalMembers: 1247,
  validators: 156,
  organizers: 42,
  activeNodes: 12,
  monthlyGrantsRemaining: 43,
  avgProcessingDays: 3.2,
  adminRatio: 0.08,
};

export const mockTransparencySummary = {
  node: { slug: 'au-nsw-sydney', name: 'Sydney Node' },
  totals: {
    inflows_30d: 1234567,
    outflows_30d: 987654,
    admin_ratio_30d: 0.08,
  },
  pools: [
    { slug: 'relief', balance: 1234500, outflows_30d: 4567800 },
    { slug: 'sovereignty', balance: 9876500, outflows_30d: 123400 },
    { slug: 'infrastructure', balance: 3456700, outflows_30d: 56700 },
  ],
  relief_capacity: {
    monthly_grants_remaining: 43,
    avg_processing_days: 3.2,
  },
  relief_metrics: {
    approval_ratio: 0.87,
    median_response_days: 2.8,
  },
};
