import {
  DiscoveredEntity,
  NodeSource,
  SeedCorpus,
  SourcePlan,
  StructuredSourceDocument,
  TopicProfile,
} from '../domain/types';
import { normalizeTopicKey, uniqueStrings } from './utils';

export function generateSeedQueries(profile: TopicProfile, seed?: SeedCorpus): string[] {
  const archetypeTerms = profile.defaultCategoryPatterns.slice(0, 3).map((pattern) => `${profile.topic} ${pattern}`);
  return uniqueStrings([
    profile.topic,
    `${profile.topic} ${profile.archetype}`,
    `${profile.topic} ${profile.entityType}`,
    ...(seed?.seedQueries ?? []),
    ...archetypeTerms,
  ]);
}

export function buildSourcePlan(profile: TopicProfile, seed?: SeedCorpus): SourcePlan {
  return {
    seedQueries: generateSeedQueries(profile, seed),
    suppliedUrls: uniqueStrings(seed?.suppliedUrls ?? []),
    sourceClasses: profile.likelySourceClasses,
    documents: seed?.documents ?? [],
  };
}

export function scoreEntityPage(document: StructuredSourceDocument): number {
  let score = 0;
  if (document.type === 'list_page' || document.sections.some((section) => section.kind === 'list')) {
    score += 4;
  }
  if (document.title && document.summary) {
    score += 3;
  }
  if (document.sections.some((section) => section.kind === 'metadata')) {
    score += 2;
  }
  if (document.breadcrumbs && document.breadcrumbs.length >= 2) {
    score += 2;
  }

  const lowerTitle = `${document.title} ${document.summary ?? ''}`.toLowerCase();
  if (['nav', 'privacy', 'cookie', 'legal', 'marketing'].some((term) => lowerTitle.includes(term))) {
    score -= 3;
  }

  return score;
}

function sourceFromDocument(document: StructuredSourceDocument, snippet?: string): Omit<NodeSource, 'id' | 'nodeId'> {
  return {
    url: document.url,
    title: document.title,
    domain: (() => {
      try {
        return new URL(document.url).hostname;
      } catch {
        return undefined;
      }
    })(),
    snippet,
    extractedAt: new Date().toISOString(),
  };
}

function inferEntityTypeFromProfile(profile: TopicProfile): string {
  return profile.entityType;
}

function buildFallbackEntity(topic: string, profile: TopicProfile): DiscoveredEntity[] {
  const base = normalizeTopicKey(topic);
  return [
    {
      label: profile.title,
      aliases: [topic],
      entityType: inferEntityTypeFromProfile(profile),
      categoryHint: profile.defaultCategoryPatterns[0],
      tags: [profile.archetype, base],
      summary: `Autogenerated draft anchor for ${profile.title}.`,
      longDescription: `No curated seed corpus was available, so Falak Map Autopilot created a deterministic starter anchor for ${profile.title}.`,
      metadata: {
        generated: true,
        topicKey: profile.topicKey,
      },
      sources: [],
      seedAxisScores: { x: 0, y: 0, z: 0 },
      seedAxisExplanations: {
        x: 'Fallback neutral placement because no direct rubric evidence was available.',
        y: 'Fallback neutral placement because no direct rubric evidence was available.',
        z: 'Fallback neutral placement because no direct rubric evidence was available.',
      },
      metrics: {
        importance: 0.6,
        popularity: 0.28,
        evidence: 0.35,
        centrality: 0.9,
        complexity: 0.42,
        controversy: 0.2,
        freshness: 0.5,
      },
      relations: [],
    },
  ];
}

export function discoverEntities(profile: TopicProfile, seed?: SeedCorpus): DiscoveredEntity[] {
  if (!seed) {
    return buildFallbackEntity(profile.topic, profile);
  }

  const documentSources = new Map<string, Omit<NodeSource, 'id' | 'nodeId'>>();
  for (const document of seed.documents) {
    const topSnippet = document.summary ?? document.sections.flatMap((section) => section.lines).slice(0, 2).join(' ');
    documentSources.set(document.id, sourceFromDocument(document, topSnippet));
  }

  const entities: DiscoveredEntity[] = seed.entities.map((entity) => ({
    label: entity.label,
    aliases: uniqueStrings([...(entity.aliases ?? []), entity.label]),
    entityType: entity.entityType ?? inferEntityTypeFromProfile(profile),
    categoryHint: entity.categoryKey,
    tags: uniqueStrings([...(entity.tags ?? []), profile.archetype]),
    summary: entity.summary,
    longDescription: entity.longDescription,
    metadata: entity.metadata ?? {},
    sources: entity.sources ?? Array.from(documentSources.values()).slice(0, 2),
    seedAxisScores: entity.axisScores,
    seedAxisExplanations: entity.axisExplanations,
    metrics: entity.metrics ?? {},
    relations: (entity.relations ?? []).map((relation) => ({
      target: relation.target,
      relation: relation.relation,
      weight: relation.weight ?? 0.5,
      confidence: relation.confidence ?? 0.6,
      evidence: relation.evidence,
    })),
  }));

  for (const document of seed.documents) {
    if (scoreEntityPage(document) < 2) {
      continue;
    }

    const entitySection = document.sections.find((section) => section.kind === 'list');
    if (!entitySection) {
      continue;
    }

    for (const line of entitySection.lines) {
      if (entities.some((entity) => entity.label.toLowerCase() === line.toLowerCase())) {
        continue;
      }

      entities.push({
        label: line,
        aliases: [line],
        entityType: inferEntityTypeFromProfile(profile),
        categoryHint: profile.defaultCategoryPatterns[0],
        tags: [profile.archetype],
        summary: document.summary,
        longDescription: undefined,
        metadata: {
          discoveredFromDocumentId: document.id,
        },
        sources: [sourceFromDocument(document, document.summary)],
        seedAxisScores: {},
        seedAxisExplanations: {},
        metrics: {
          importance: 0.42,
          popularity: 0.18,
          evidence: 0.3,
          centrality: 0.2,
          complexity: 0.28,
          controversy: 0.12,
          freshness: 0.24,
        },
        relations: [],
      });
    }
  }

  return entities;
}
