import { SeedCorpus } from '../domain/types';
import { LEFT_THOUGHT_GRAPH_SEED } from './leftThoughtSeed';

export const MAP_MOCK_SEEDS: SeedCorpus[] = [
  LEFT_THOUGHT_GRAPH_SEED,
  {
    topicKey: 'consciousness-theories',
    title: 'Consciousness Theories',
    archetype: 'theory',
    description: 'A structured comparison of major theories of consciousness and their evidentiary posture.',
    suppliedUrls: [
      'https://example.org/reference/consciousness-theories',
      'https://example.org/survey/neuroscience-consciousness',
    ],
    documents: [
      {
        id: 'cons-list',
        url: 'https://example.org/reference/consciousness-theories',
        title: 'Reference Guide to Consciousness Theories',
        type: 'list_page',
        summary: 'Overview of major theories, variants, and critiques.',
        breadcrumbs: ['Reference', 'Mind', 'Consciousness'],
        sections: [
          {
            heading: 'Theories',
            kind: 'list',
            lines: [
              'Global Workspace Theory',
              'Integrated Information Theory',
              'Predictive Processing',
              'Higher-Order Thought',
              'Enactivism',
              'Panpsychism',
            ],
          },
        ],
      },
      {
        id: 'cons-survey',
        url: 'https://example.org/survey/neuroscience-consciousness',
        title: 'Neuroscience Survey of Consciousness Research',
        type: 'reference',
        summary: 'Survey discussing empirical backing and debates across consciousness research.',
        sections: [
          {
            heading: 'Summary',
            kind: 'summary',
            lines: [
              'Global Workspace Theory is widely used in cognitive neuroscience.',
              'Integrated Information Theory emphasizes intrinsic causal structure.',
              'Predictive Processing models perception as hierarchical prediction.',
              'Panpsychism is often framed as more speculative than empirical.',
            ],
          },
        ],
      },
    ],
    entities: [
      {
        label: 'Global Workspace Theory',
        aliases: ['GWT'],
        categoryKey: 'schools',
        tags: ['cognitive-science', 'broadcasting', 'attention'],
        summary: 'Frames consciousness as globally broadcast information within a cognitive workspace.',
        axisScores: { x: -0.1, y: 0.5, z: 0.7 },
        axisExplanations: {
          x: 'Often framed in cognitive-functional terms rather than metaphysical ones.',
          y: 'Applied across multiple mental phenomena.',
          z: 'Commonly discussed with empirical paradigms and experiments.',
        },
        metrics: {
          importance: 0.88,
          popularity: 0.82,
          evidence: 0.8,
          centrality: 0.72,
          complexity: 0.62,
          controversy: 0.38,
          freshness: 0.54,
        },
        sources: [
          {
            url: 'https://example.org/reference/consciousness-theories#gwt',
            title: 'Reference Guide to Consciousness Theories',
            snippet: 'Global Workspace Theory models conscious access as global availability.',
          },
        ],
        relations: [
          { target: 'Predictive Processing', relation: 'similar_to', weight: 0.54, confidence: 0.7, evidence: 'Both are used in cognitive modeling.' },
          { target: 'Integrated Information Theory', relation: 'contradicts', weight: 0.62, confidence: 0.72, evidence: 'They explain consciousness with different primitives.' },
        ],
      },
      {
        label: 'Integrated Information Theory',
        aliases: ['IIT'],
        categoryKey: 'schools',
        tags: ['information', 'causal-structure', 'phi'],
        summary: 'Ties consciousness to integrated causal structure and informational unity.',
        axisScores: { x: 0.6, y: 0.7, z: 0.45 },
        axisExplanations: {
          x: 'Often presented with stronger metaphysical commitments.',
          y: 'Claims broad explanatory scope.',
          z: 'Empirical testing is active but contested.',
        },
        metrics: {
          importance: 0.86,
          popularity: 0.76,
          evidence: 0.58,
          centrality: 0.74,
          complexity: 0.84,
          controversy: 0.72,
          freshness: 0.63,
        },
        relations: [
          { target: 'Panpsychism', relation: 'similar_to', weight: 0.48, confidence: 0.61, evidence: 'Both are read as opening toward broad metaphysical consciousness claims.' },
        ],
      },
      {
        label: 'Predictive Processing',
        categoryKey: 'methods',
        tags: ['prediction', 'perception', 'bayesian'],
        summary: 'Models cognition through hierarchical prediction and error correction.',
        axisScores: { x: -0.2, y: 0.68, z: 0.76 },
        metrics: {
          importance: 0.81,
          popularity: 0.79,
          evidence: 0.77,
          centrality: 0.66,
          complexity: 0.7,
          controversy: 0.41,
          freshness: 0.67,
        },
        relations: [
          { target: 'Enactivism', relation: 'extends', weight: 0.44, confidence: 0.58, evidence: 'Some interpretations blend predictive and embodied approaches.' },
        ],
      },
      {
        label: 'Higher-Order Thought',
        aliases: ['HOT'],
        categoryKey: 'schools',
        tags: ['meta-representation', 'philosophy'],
        summary: 'Treats consciousness as depending on higher-order representation of mental states.',
        axisScores: { x: 0.15, y: 0.42, z: 0.52 },
        metrics: {
          importance: 0.72,
          popularity: 0.58,
          evidence: 0.49,
          centrality: 0.43,
          complexity: 0.57,
          controversy: 0.46,
          freshness: 0.42,
        },
      },
      {
        label: 'Enactivism',
        categoryKey: 'applications',
        tags: ['embodiment', 'ecology', 'sense-making'],
        summary: 'Locates cognition and conscious meaning-making in embodied action and environment.',
        axisScores: { x: -0.05, y: 0.55, z: 0.63 },
        metrics: {
          importance: 0.69,
          popularity: 0.55,
          evidence: 0.57,
          centrality: 0.49,
          complexity: 0.61,
          controversy: 0.39,
          freshness: 0.59,
        },
      },
      {
        label: 'Panpsychism',
        categoryKey: 'critics',
        tags: ['metaphysics', 'ubiquity'],
        summary: 'Argues that mind-like properties are fundamental and widespread in nature.',
        axisScores: { x: 0.95, y: 0.82, z: -0.1 },
        metrics: {
          importance: 0.63,
          popularity: 0.5,
          evidence: 0.22,
          centrality: 0.36,
          complexity: 0.58,
          controversy: 0.83,
          freshness: 0.44,
        },
      },
    ],
  },
  {
    topicKey: 'ancient-levantine-deities',
    title: 'Ancient Levantine Deities',
    archetype: 'myth',
    description: 'A semantic constellation of deities, cult centers, and cosmological associations across the ancient Levant.',
    suppliedUrls: [
      'https://example.org/ancient-levant/deities',
      'https://example.org/ancient-levant/cult-centers',
    ],
    documents: [
      {
        id: 'lev-list',
        url: 'https://example.org/ancient-levant/deities',
        title: 'Levantine Deity Index',
        type: 'list_page',
        summary: 'List of major deities and epithets in Levantine traditions.',
        breadcrumbs: ['Ancient Near East', 'Levant', 'Deities'],
        sections: [
          {
            heading: 'Primary Figures',
            kind: 'list',
            lines: ['El', 'Baal Hadad', 'Anat', 'Astarte', 'Yam', 'Mot', 'Shapash'],
          },
        ],
      },
    ],
    entities: [
      {
        label: 'El',
        categoryKey: 'deities',
        tags: ['creator', 'high-god', 'ancestral'],
        summary: 'High god figure associated with kingship, ancestry, and divine council leadership.',
        axisScores: { x: 0.65, y: 0.72, z: 0.84 },
        metrics: {
          importance: 0.91,
          popularity: 0.52,
          evidence: 0.73,
          centrality: 0.88,
          complexity: 0.49,
          controversy: 0.37,
          freshness: 0.16,
        },
        relations: [
          { target: 'Baal Hadad', relation: 'influences', weight: 0.76, confidence: 0.78, evidence: 'Baal narratives operate within El’s wider divine order.' },
          { target: 'Anat', relation: 'belongs_to', weight: 0.38, confidence: 0.57, evidence: 'Anat appears within the same mythic council environment.' },
        ],
      },
      {
        label: 'Baal Hadad',
        aliases: ['Baal'],
        categoryKey: 'deities',
        tags: ['storm', 'fertility', 'kingship'],
        summary: 'Storm deity strongly associated with rain, fertility, and royal power.',
        axisScores: { x: 0.42, y: 0.18, z: 0.58 },
        metrics: {
          importance: 0.9,
          popularity: 0.68,
          evidence: 0.78,
          centrality: 0.84,
          complexity: 0.53,
          controversy: 0.42,
          freshness: 0.14,
        },
        relations: [
          { target: 'Yam', relation: 'contradicts', weight: 0.85, confidence: 0.82, evidence: 'Baal is mythically opposed to Yam.' },
          { target: 'Mot', relation: 'contradicts', weight: 0.78, confidence: 0.78, evidence: 'Baal’s death-and-return cycle is entangled with Mot.' },
          { target: 'Anat', relation: 'co_occurs_with', weight: 0.66, confidence: 0.74, evidence: 'Anat and Baal appear together in key cycles.' },
        ],
      },
      {
        label: 'Anat',
        categoryKey: 'deities',
        tags: ['war', 'protection', 'kinship'],
        summary: 'Warrior goddess associated with ferocity, protection, and kinship to Baal.',
        axisScores: { x: 0.22, y: 0.08, z: 0.34 },
        metrics: {
          importance: 0.7,
          popularity: 0.44,
          evidence: 0.63,
          centrality: 0.58,
          complexity: 0.51,
          controversy: 0.29,
          freshness: 0.12,
        },
      },
      {
        label: 'Astarte',
        categoryKey: 'deities',
        tags: ['love', 'war', 'transregional'],
        summary: 'A goddess whose cultic profile spans multiple Levantine and Mediterranean settings.',
        axisScores: { x: 0.86, y: 0.14, z: 0.22 },
        metrics: {
          importance: 0.74,
          popularity: 0.49,
          evidence: 0.61,
          centrality: 0.55,
          complexity: 0.47,
          controversy: 0.34,
          freshness: 0.1,
        },
      },
      {
        label: 'Yam',
        categoryKey: 'symbols',
        tags: ['sea', 'chaos', 'adversary'],
        summary: 'Sea-associated force often framed as a cosmic rival in storm-god narratives.',
        axisScores: { x: 0.28, y: 0.56, z: 0.9 },
        metrics: {
          importance: 0.65,
          popularity: 0.33,
          evidence: 0.58,
          centrality: 0.51,
          complexity: 0.42,
          controversy: 0.31,
          freshness: 0.08,
        },
      },
      {
        label: 'Mot',
        categoryKey: 'symbols',
        tags: ['death', 'underworld', 'seasonality'],
        summary: 'Deity associated with death and the underworld in seasonal cycles.',
        axisScores: { x: 0.34, y: -0.84, z: 0.72 },
        metrics: {
          importance: 0.68,
          popularity: 0.31,
          evidence: 0.56,
          centrality: 0.54,
          complexity: 0.45,
          controversy: 0.28,
          freshness: 0.07,
        },
      },
      {
        label: 'Shapash',
        categoryKey: 'symbols',
        tags: ['sun', 'mediation', 'witness'],
        summary: 'Solar deity often functioning as witness, messenger, and mediator between realms.',
        axisScores: { x: 0.18, y: 0.74, z: 0.48 },
        metrics: {
          importance: 0.61,
          popularity: 0.23,
          evidence: 0.52,
          centrality: 0.42,
          complexity: 0.38,
          controversy: 0.16,
          freshness: 0.06,
        },
      },
    ],
  },
  {
    topicKey: 'software-architecture-patterns',
    title: 'Software Architecture Patterns',
    archetype: 'technology',
    description: 'A comparative map of architecture patterns, tradeoffs, and dependencies.',
    documents: [
      {
        id: 'arch-list',
        url: 'https://example.org/software-architecture/patterns',
        title: 'Software Architecture Pattern Catalogue',
        type: 'list_page',
        summary: 'Catalog of common software architecture patterns.',
        sections: [
          {
            heading: 'Patterns',
            kind: 'list',
            lines: [
              'Monolith',
              'Modular Monolith',
              'Microservices',
              'Event-Driven Architecture',
              'Hexagonal Architecture',
              'CQRS',
              'Serverless',
            ],
          },
        ],
      },
    ],
    entities: [
      {
        label: 'Monolith',
        categoryKey: 'patterns',
        tags: ['deployment', 'simplicity'],
        summary: 'A single deployable application boundary with tightly coupled runtime composition.',
        axisScores: { x: -0.85, y: 0.7, z: -0.6 },
        metrics: {
          importance: 0.79,
          popularity: 0.74,
          evidence: 0.82,
          centrality: 0.61,
          complexity: 0.39,
          controversy: 0.31,
          freshness: 0.48,
        },
        relations: [
          { target: 'Modular Monolith', relation: 'extends', weight: 0.73, confidence: 0.81, evidence: 'Modular monolith keeps the single deployable boundary while improving internal separation.' },
        ],
      },
      {
        label: 'Modular Monolith',
        categoryKey: 'patterns',
        tags: ['modularity', 'single-deployable'],
        summary: 'A monolith with explicit bounded modules and internal contracts.',
        axisScores: { x: -0.35, y: 0.8, z: -0.15 },
        metrics: {
          importance: 0.82,
          popularity: 0.61,
          evidence: 0.79,
          centrality: 0.7,
          complexity: 0.56,
          controversy: 0.2,
          freshness: 0.64,
        },
      },
      {
        label: 'Microservices',
        categoryKey: 'patterns',
        tags: ['distribution', 'autonomy', 'scaling'],
        summary: 'Decomposes systems into separately deployable services with explicit network boundaries.',
        axisScores: { x: 0.72, y: 0.92, z: 0.8 },
        metrics: {
          importance: 0.88,
          popularity: 0.84,
          evidence: 0.73,
          centrality: 0.76,
          complexity: 0.92,
          controversy: 0.61,
          freshness: 0.59,
        },
      },
      {
        label: 'Event-Driven Architecture',
        categoryKey: 'protocols',
        tags: ['events', 'async', 'integration'],
        summary: 'Coordinates workflows through events and asynchronous consumers.',
        axisScores: { x: 0.41, y: 0.65, z: 0.53 },
        metrics: {
          importance: 0.84,
          popularity: 0.72,
          evidence: 0.74,
          centrality: 0.67,
          complexity: 0.78,
          controversy: 0.38,
          freshness: 0.68,
        },
      },
      {
        label: 'Hexagonal Architecture',
        aliases: ['Ports and Adapters'],
        categoryKey: 'tradeoffs',
        tags: ['boundaries', 'testability'],
        summary: 'Centers the domain model and isolates infrastructure behind ports and adapters.',
        axisScores: { x: 0.12, y: 0.48, z: 0.36 },
        metrics: {
          importance: 0.73,
          popularity: 0.58,
          evidence: 0.69,
          centrality: 0.52,
          complexity: 0.63,
          controversy: 0.18,
          freshness: 0.57,
        },
      },
      {
        label: 'CQRS',
        categoryKey: 'protocols',
        tags: ['segregation', 'read-models', 'write-models'],
        summary: 'Separates command and query responsibilities to optimize complex domains.',
        axisScores: { x: 0.18, y: 0.43, z: 0.66 },
        metrics: {
          importance: 0.69,
          popularity: 0.43,
          evidence: 0.55,
          centrality: 0.46,
          complexity: 0.75,
          controversy: 0.44,
          freshness: 0.52,
        },
      },
      {
        label: 'Serverless',
        categoryKey: 'patterns',
        tags: ['managed', 'elastic', 'functions'],
        summary: 'Relies on managed execution platforms and event-triggered compute primitives.',
        axisScores: { x: 0.24, y: 0.88, z: 0.12 },
        metrics: {
          importance: 0.77,
          popularity: 0.71,
          evidence: 0.66,
          centrality: 0.57,
          complexity: 0.58,
          controversy: 0.32,
          freshness: 0.7,
        },
      },
    ],
  },
  {
    topicKey: 'toy-commons-loop',
    title: 'Toy Commons Loop',
    archetype: 'ecosystem',
    description: 'A tiny seed map for rapid sandbox rendering and editor verification.',
    documents: [
      {
        id: 'toy-loop',
        url: 'https://example.org/toy-commons-loop',
        title: 'Toy Commons Loop',
        type: 'source_pack',
        summary: 'Minimal three-node loop used for local Falak map sandbox verification.',
        sections: [
          {
            heading: 'Loop',
            kind: 'list',
            lines: ['Community Need', 'Care Guild', 'Tool Library'],
          },
        ],
      },
    ],
    entities: [
      {
        label: 'Community Need',
        categoryKey: 'signals',
        tags: ['need', 'signal'],
        summary: 'The initiating signal that something in the commons needs care.',
        axisScores: { x: -0.4, y: 0.2, z: 0.3 },
        metrics: {
          importance: 0.72,
          popularity: 0.41,
          evidence: 0.52,
          centrality: 0.66,
          complexity: 0.24,
          controversy: 0.08,
          freshness: 0.61,
        },
        relations: [
          { target: 'Care Guild', relation: 'influences', weight: 0.84, confidence: 0.82, evidence: 'Needs trigger coordinated care work.' },
        ],
      },
      {
        label: 'Care Guild',
        categoryKey: 'actors',
        tags: ['coordination', 'stewardship'],
        summary: 'A small stewarding group that interprets need and mobilizes response.',
        axisScores: { x: 0.15, y: 0.64, z: 0.48 },
        metrics: {
          importance: 0.76,
          popularity: 0.46,
          evidence: 0.57,
          centrality: 0.71,
          complexity: 0.33,
          controversy: 0.11,
          freshness: 0.55,
        },
        relations: [
          { target: 'Tool Library', relation: 'extends', weight: 0.72, confidence: 0.78, evidence: 'Guild activity routes into shared tools and logistics.' },
        ],
      },
      {
        label: 'Tool Library',
        categoryKey: 'infrastructure',
        tags: ['infrastructure', 'shared-assets'],
        summary: 'Shared practical infrastructure that closes the loop back into community readiness.',
        axisScores: { x: 0.35, y: -0.1, z: 0.18 },
        metrics: {
          importance: 0.68,
          popularity: 0.38,
          evidence: 0.61,
          centrality: 0.63,
          complexity: 0.29,
          controversy: 0.05,
          freshness: 0.49,
        },
        relations: [
          { target: 'Community Need', relation: 'co_occurs_with', weight: 0.58, confidence: 0.73, evidence: 'Shared infrastructure often emerges from repeated needs.' },
        ],
      },
    ],
  },
];

export function findMockSeed(topicKey: string): SeedCorpus | undefined {
  return MAP_MOCK_SEEDS.find((seed) => seed.topicKey === topicKey);
}
