import {
  bindArrangerPieceToHost,
  createArrangerPieceLibraryItem,
  defaultArrangementKindForHost,
  setArrangerPieceGarmentArtwork,
} from "../arranger.ts";
import { SPATIAL_SCHEMA_VERSION, type SpatialGarmentArticleType, type SpatialRoomDefinition } from "../model.ts";

/**
 * Internal evidence rack for the alpha-masked garment artwork pass.
 *
 * Every image here is synthetic test media generated by
 * `scripts/generate-alpha-garment-test-media.mjs`: flat procedural shapes with a
 * baked "TEST" wordmark and a transparent background. None of it is Mobstar
 * product artwork, and nothing in this fixture asserts a real product fact.
 *
 * The fixture exists to prove one thing in the rendered lane: the artwork alpha
 * channel, not the plane, defines the visible garment silhouette.
 *
 * It is assembled by replaying the real operator mutations — create a Piece
 * Library item, assign garment artwork, bind it to the rack — rather than by
 * hand-writing bindings, so it cannot drift away from what the arranger UI
 * actually produces. Those mutations use a fixed timestamp, so the result is
 * deterministic.
 */

/** Byte sizes are asserted against the real files by `alphaGarmentArtwork.test.ts`. */
const ALPHA_MEDIA = [
  { article: "shirt", face: "front", file: "shirt-front-alpha.png", bytes: 1_595 },
  { article: "shirt", face: "back", file: "shirt-back-alpha.png", bytes: 1_556 },
  { article: "pant", face: "front", file: "pant-front-alpha.png", bytes: 1_734 },
  { article: "pant", face: "back", file: "pant-back-alpha.png", bytes: 1_682 },
  { article: "generic", face: "front", file: "generic-front-alpha.png", bytes: 1_698 },
  { article: "generic", face: "back", file: "generic-back-alpha.png", bytes: 1_590 },
  { article: "shoe", face: "display", file: "shoe-display-alpha.png", bytes: 1_121 },
] as const;

export const ALPHA_GARMENT_MEDIA_DIRECTORY = "presence-spatial/internal-evidence/alpha-garments";

const ALPHA_ATTRIBUTION = "Synthetic alpha-masked garment test artwork (internal evidence, not product artwork)";

function assetId(entry: (typeof ALPHA_MEDIA)[number]): string {
  return `alpha-${entry.article}-${entry.face}`;
}

function mediaId(entry: (typeof ALPHA_MEDIA)[number]): string {
  return `alpha-media-${entry.article}-${entry.face}`;
}

const BASE_ROOM = {
  schemaVersion: SPATIAL_SCHEMA_VERSION,
  id: "alpha-garment-rack-evidence-room",
  label: "Alpha-masked garment rack (internal evidence)",
  fixtureKind: "mobstar-proof",
  revision: 1,
  seed: "alpha-garment-rack-v1",
  bounds: { width: 18, height: 6, depth: 30 },
  entryStateId: "overview",
  lightingProfileId: "lookbook-rack-warm" as const,
  cameraPath: { points: [[0, 2, 12], [0, 2, 6], [0, 2, -1]], clearance: 0.4 },
  assets: ALPHA_MEDIA.map((entry) => ({
    id: assetId(entry),
    kind: "image" as const,
    locator: `public:${ALPHA_GARMENT_MEDIA_DIRECTORY}/${entry.file}`,
    safety: "public-safe" as const,
    compressedBytes: entry.bytes,
    eager: true,
    attribution: ALPHA_ATTRIBUTION,
  })),
  skins: [
    {
      id: "alpha-evidence-skin",
      label: "Alpha evidence lookbook skin",
      // The `lookbook-rack` style treatment: readable architecture and steel
      // fixtures, with the rack riser kept subordinate to the artwork.
      materialPresets: {
        wall: "wall-lookbook-graphite" as const,
        floor: "floor-lookbook-slate" as const,
        tabletop: "tabletop-lookbook-riser" as const,
        "rack-metal": "rack-lookbook-steel" as const,
        fabric: "fabric-neutral" as const,
      },
      colors: {},
      decalAssetIds: [],
    },
  ],
  media: ALPHA_MEDIA.map((entry) => ({
    id: mediaId(entry),
    kind: "image" as const,
    assetId: assetId(entry),
    alt: `Synthetic alpha-masked ${entry.article} ${entry.face} test artwork`,
    safety: "public-safe" as const,
  })),
  actions: [
    { id: "go-rack", kind: "navigate-state" as const, label: "Focus the garment rack", targetStateId: "rack-focus" },
  ],
  placements: [
    { id: "room-shell", order: 0, componentId: "presence.room-shell", version: "1.0.0", transform: { position: [0, 3, 0] as [number, number, number], rotation: [0, 0, 0] as [number, number, number], scale: [1, 1, 1] as [number, number, number] }, anchor: { kind: "free" as const }, materialSlotOverrides: { wall: "wall-lookbook-graphite" as const }, skinRef: "alpha-evidence-skin", actionRefs: [], visible: true, semanticLabel: "Dark internal room shell" },
    { id: "floor", order: 1, componentId: "presence.floor-slab", version: "1.0.0", transform: { position: [0, 0.06, 0] as [number, number, number], rotation: [0, 0, 0] as [number, number, number], scale: [1, 1, 1] as [number, number, number] }, anchor: { kind: "floor" as const }, materialSlotOverrides: { floor: "floor-lookbook-slate" as const }, skinRef: "alpha-evidence-skin", actionRefs: [], visible: true, semanticLabel: "Dark stone floor" },
    { id: "garment-rack", order: 2, componentId: "presence.suspended-rack", version: "1.0.0", transform: { position: [0, 2.1, -7] as [number, number, number], rotation: [0, 0, 0] as [number, number, number], scale: [1, 1, 1] as [number, number, number] }, anchor: { kind: "floor" as const }, materialSlotOverrides: { "rack-metal": "rack-lookbook-steel" as const, tabletop: "tabletop-lookbook-riser" as const }, skinRef: "alpha-evidence-skin", actionRefs: ["go-rack"], visible: true, semanticLabel: "Suspended garment rack carrying alpha-masked test artwork" },
  ],
  states: [
    { id: "overview", label: "Overview", cameraPosition: [0, 3.4, 12] as [number, number, number], cameraTarget: [0, 2.2, -7] as [number, number, number], fieldOfView: 55, reducedMotionStateId: "overview-static" },
    { id: "overview-static", label: "Overview without motion", cameraPosition: [0, 3.4, 12] as [number, number, number], cameraTarget: [0, 2.2, -7] as [number, number, number], fieldOfView: 55 },
    { id: "rack-focus", label: "Garment rack focus", cameraPosition: [0, 2.9, -1.1] as [number, number, number], cameraTarget: [0, 2.48, -7] as [number, number, number], fieldOfView: 48, focusPlacementId: "garment-rack", reducedMotionStateId: "rack-static" },
    { id: "rack-static", label: "Garment rack without motion", cameraPosition: [0, 2.9, -1.1] as [number, number, number], cameraTarget: [0, 2.48, -7] as [number, number, number], fieldOfView: 48, focusPlacementId: "garment-rack" },
  ],
  semanticFallback: [
    { placementId: "garment-rack", label: "Alpha-masked garment rack", description: "Open the rack-focused state.", actionRefs: ["go-rack"] },
  ],
} satisfies SpatialRoomDefinition;

interface GarmentSeed {
  label: string;
  article: SpatialGarmentArticleType;
  /** Absent artwork is deliberate on one garment, to keep the warning honest. */
  artwork?: {
    frontImageRef?: string;
    backImageRef?: string;
    displayImageRef?: string;
  };
  href?: string;
  actionLabel?: string;
}

const GARMENT_SEEDS: readonly GarmentSeed[] = [
  {
    label: "Look 01 Alpha shirt (front + back)",
    article: "shirt",
    artwork: { frontImageRef: "alpha-media-shirt-front", backImageRef: "alpha-media-shirt-back" },
    // One action link, to prove actions survive into the fallback.
    href: "https://example.com/internal-evidence/look-01",
    actionLabel: "Open Look 01",
  },
  {
    // Front only: the back reuses the front, which is the documented fallback.
    label: "Look 02 Alpha shirt (front only)",
    article: "shirt",
    artwork: { frontImageRef: "alpha-media-shirt-front" },
  },
  {
    label: "Look 03 Alpha pant (front + back)",
    article: "pant",
    artwork: { frontImageRef: "alpha-media-pant-front", backImageRef: "alpha-media-pant-back" },
  },
  {
    label: "Look 04 Alpha generic (front + back)",
    article: "generic",
    artwork: { frontImageRef: "alpha-media-generic-front", backImageRef: "alpha-media-generic-back" },
  },
  {
    label: "Look 05 Alpha shoe (display)",
    article: "shoe",
    artwork: { displayImageRef: "alpha-media-shoe-display" },
  },
  {
    // Deliberately unassigned, so `missingArtwork` stays provably honest.
    label: "Look 06 No artwork assigned",
    article: "shirt",
  },
];

function buildAlphaGarmentRack(): SpatialRoomDefinition {
  let room: SpatialRoomDefinition = BASE_ROOM;
  const host = room.placements.find((placement) => placement.id === "garment-rack");
  if (!host) throw new Error("Alpha garment rack fixture must contain its rack host.");
  const arrangementKind = defaultArrangementKindForHost(host);

  for (const seed of GARMENT_SEEDS) {
    const created = createArrangerPieceLibraryItem(room, {
      pieceType: "garment",
      label: seed.label,
      safety: "public-safe",
      ...(seed.href ? { actionKind: "open-link" as const, href: seed.href, actionLabel: seed.actionLabel } : {}),
    });
    if (!created.ok) throw new Error(`Alpha fixture piece failed: ${JSON.stringify(created.issues)}`);
    room = created.room;

    const piece = room.pieceLibrary?.[room.pieceLibrary.length - 1];
    if (!piece) throw new Error("Alpha fixture piece was not appended to the Piece Library.");

    const artwork = setArrangerPieceGarmentArtwork(room, piece.id, {
      garmentArticleType: seed.article,
      ...(seed.artwork ?? {}),
    });
    if (!artwork.ok) throw new Error(`Alpha fixture artwork failed: ${JSON.stringify(artwork.issues)}`);
    room = artwork.room;

    const bound = bindArrangerPieceToHost(room, host.id, { pieceId: piece.id, arrangementKind });
    if (!bound.ok) throw new Error(`Alpha fixture binding failed: ${JSON.stringify(bound.issues)}`);
    room = bound.room;
  }

  return room;
}

export const ALPHA_GARMENT_RACK_FIXTURE: SpatialRoomDefinition = buildAlphaGarmentRack();
